#if !canImport(ObjectiveC)
import XCTest

extension ArrayCompareTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayCompareTests = [
        ("test_differentLengths", test_differentLengths),
        ("test_differentValues", test_differentValues),
        ("test_reducePrebuilt", test_reducePrebuilt),
        ("test_same", test_same),
    ]
}

extension Attribute_LiteralTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Attribute_LiteralTests = [
        ("test_ArrayLiteral", test_ArrayLiteral),
        ("test_BooleanLiteral", test_BooleanLiteral),
        ("test_DictionaryLiteral", test_DictionaryLiteral),
        ("test_FloatLiteral", test_FloatLiteral),
        ("test_IntegerLiteral", test_IntegerLiteral),
        ("test_NilLiteral", test_NilLiteral),
        ("test_NullableArrayLiteral", test_NullableArrayLiteral),
        ("test_NullableBooleanLiteral", test_NullableBooleanLiteral),
        ("test_NullableDictionaryLiteral", test_NullableDictionaryLiteral),
        ("test_NullableFloatLiteral", test_NullableFloatLiteral),
        ("test_NullableIntegerLiteral", test_NullableIntegerLiteral),
        ("test_NullableOptionalArrayLiteral", test_NullableOptionalArrayLiteral),
        ("test_NullableOptionalBooleanLiteral", test_NullableOptionalBooleanLiteral),
        ("test_NullableOptionalDictionaryLiteral", test_NullableOptionalDictionaryLiteral),
        ("test_NullableOptionalFloatLiteral", test_NullableOptionalFloatLiteral),
        ("test_NullableOptionalIntegerLiteral", test_NullableOptionalIntegerLiteral),
        ("test_NullableOptionalStringLiteral", test_NullableOptionalStringLiteral),
        ("test_NullableStringLiteral", test_NullableStringLiteral),
        ("test_OptionalArrayLiteral", test_OptionalArrayLiteral),
        ("test_OptionalBooleanLiteral", test_OptionalBooleanLiteral),
        ("test_OptionalDictionaryLiteral", test_OptionalDictionaryLiteral),
        ("test_OptionalFloatLiteral", test_OptionalFloatLiteral),
        ("test_OptionalIntegerLiteral", test_OptionalIntegerLiteral),
        ("test_OptionalNilLiteral", test_OptionalNilLiteral),
        ("test_OptionalStringLiteral", test_OptionalStringLiteral),
        ("test_StringLiteral", test_StringLiteral),
    ]
}

extension AttributesCompareTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AttributesCompareTests = [
        ("test_differentAttributes", test_differentAttributes),
        ("test_nonAttributeTypes", test_nonAttributeTypes),
        ("test_sameAttributes", test_sameAttributes),
    ]
}

extension DocumentCompareTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DocumentCompareTests = [
        ("test_differentAPIDescription", test_differentAPIDescription),
        ("test_differentData", test_differentData),
        ("test_differentErrors", test_differentErrors),
        ("test_differentLinks", test_differentLinks),
        ("test_differentMetadata", test_differentMetadata),
        ("test_errorAndData", test_errorAndData),
        ("test_same", test_same),
        ("test_sameErrorsDifferentMetadata", test_sameErrorsDifferentMetadata),
    ]
}

extension EntityCheckTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EntityCheckTests = [
        ("test_failsWithBadAttribute", test_failsWithBadAttribute),
        ("test_failsWithBadRelationship", test_failsWithBadRelationship),
        ("test_failsWithEnumAttributes", test_failsWithEnumAttributes),
        ("test_failsWithEnumRelationships", test_failsWithEnumRelationships),
        ("test_failsWithOptionalArrayAttribute", test_failsWithOptionalArrayAttribute),
    ]
}

extension Id_LiteralTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Id_LiteralTests = [
        ("test_IntegerLiteral", test_IntegerLiteral),
        ("test_StringLiteral", test_StringLiteral),
    ]
}

extension IncludesCompareTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IncludesCompareTests = [
        ("test_missing", test_missing),
        ("test_same", test_same),
        ("test_typeMismatch", test_typeMismatch),
        ("test_valueMismatch", test_valueMismatch),
    ]
}

extension Relationship_LiteralTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Relationship_LiteralTests = [
        ("test_ArrayLiteral", test_ArrayLiteral),
        ("test_NilLiteral", test_NilLiteral),
        ("test_StringLiteral", test_StringLiteral),
    ]
}

extension RelationshipsCompareTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RelationshipsCompareTests = [
        ("test_differentIds", test_differentIds),
        ("test_differentLinks", test_differentLinks),
        ("test_differentMetadata", test_differentMetadata),
        ("test_nonRelationshipTypes", test_nonRelationshipTypes),
        ("test_same", test_same),
    ]
}

extension ResourceObjectCompareTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResourceObjectCompareTests = [
        ("test_differentAttributes", test_differentAttributes),
        ("test_differentIds", test_differentIds),
        ("test_differentLinks", test_differentLinks),
        ("test_differentMetadata", test_differentMetadata),
        ("test_differentRelationships", test_differentRelationships),
        ("test_same", test_same),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArrayCompareTests.__allTests__ArrayCompareTests),
        testCase(Attribute_LiteralTests.__allTests__Attribute_LiteralTests),
        testCase(AttributesCompareTests.__allTests__AttributesCompareTests),
        testCase(DocumentCompareTests.__allTests__DocumentCompareTests),
        testCase(EntityCheckTests.__allTests__EntityCheckTests),
        testCase(Id_LiteralTests.__allTests__Id_LiteralTests),
        testCase(IncludesCompareTests.__allTests__IncludesCompareTests),
        testCase(Relationship_LiteralTests.__allTests__Relationship_LiteralTests),
        testCase(RelationshipsCompareTests.__allTests__RelationshipsCompareTests),
        testCase(ResourceObjectCompareTests.__allTests__ResourceObjectCompareTests),
    ]
}
#endif
