name: Tests

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.2-focal
          - swift:5.2-centos8
          - swift:5.3-focal
          - swift:5.3-centos8
          - swift:5.4-focal
          - swift:5.4-centos8
          - swift:5.5-focal
          - swift:5.5-centos8
          - swift:5.6-focal
#          - swift:5.7-focal
#          - swift:5.8-focal
#          - swift:5.9-focal
#          - swift:5.10-focal
    container: ${{ matrix.image }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: swift test --enable-test-discovery
  osx:
    runs-on: macOS-latest
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with: { 'xcode-version': 'latest' }
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: swift test --enable-test-discovery
